#!/bin/sh

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

# --- Запрет пуша в main ---
protected_branch="refs/heads/main"

while read local_ref local_oid remote_ref remote_oid
do
    # Если пушим в main → ошибка
    if [ "$remote_ref" = "$protected_branch" ]; then
        echo "Push to 'main' is forbidden. Please create a feature branch and open a PR."
        exit 1
    fi

    if test "$local_oid" = "$zero"
    then
        # Handle delete
        :
    else
        if test "$remote_oid" = "$zero"
        then
            # New branch, examine all commits
            range="$local_oid"
        else
            # Update to existing branch, examine new commits
            range="$remote_oid..$local_oid"
        fi

        # Проверка на WIP в сообщениях коммитов
        commit=$(git rev-list -n 1 --grep '^WIP' "$range")
        if test -n "$commit"
        then
            echo >&2 "Found WIP commit in $local_ref, not pushing"
            exit 1
        fi
    fi
done

exit 0
